### PR TITLE
New Infrastructure and API

### LINKED ISSUE #28: Improvements to Continuous Integration
It would be ideal to have a submodule for libui, and then build libui using TravisCI and Appveyor. This would make releasing the binaries for libui (and keeping the libraries up-to-date) a whole lot easier. 

The downside is I know nothing about CMake, nor TravisCI, so this is definitely out of my scope for now.

### LINKED ISSUE #29: Hide the Console Window on startup
This seems to be a looming issue with .NET Core, since you can only compile as a library or console application. I would love to do it programatically, rather than try to use `binedit.exe` or whatever `NSubsys` is (which may be an option).

This is definitely a help wanted issue, as I'm not quite sure where to start with this. At least there's a simple way on Windows to accomplish this.

### LINKED ISSUE #36: Nuget?
**Is your feature request related to a problem? Please describe.**
Kinda. can you upload this to nuget?

**Describe the solution you'd like**
Upload as .net 5 nuget package

**Describe alternatives you've considered**
I have considered Eto.Forms but its too complicated.

**Additional Information**
Please separate stable and unstable releases

### LINKED ISSUE #37: Custom NativeLibraryLoader Implementation
This will allow for using the new C# unmanaged delegates as function pointers, rather than just IntPtr or void*. Hoping for a performane boost from it.

I also plan on adding FreeBSD/macOS support for it.

### LINKED ISSUE #42: Add SourceLink to the build
More Information: https://github.com/dotnet/sourcelink

### PR DESCRIPTION
**Pull request by simplexidev**
Closes #28
Closes #29
Closes #36
Closes #37
Closes #42

This is going to be a big PR, with breaking changes to the build routine and API structure. Here's the TODO list, which will be updated and added to. 

The name change *will* be incorporated into this pull request. The namespace `LibUISharp` will change to `SimplexiDev`, and the project will be renamed to `SimplexiDev Framework`, or `sdfx` for short.

The new CI pipelines *will not* be considered complete until after the name change, due to the new (renamed) pipelines and new directories for it. As such, they aren't tested, so post-merge modifications may be required once this PR is merged.

- [x] Update to .NET 6.0
- [x] Update the Code of Conduct
- [x] Add external submodules for `libui`, `miniaudio`, and `zstd`.
- [x] Update the Third Party Notices file, as I am rewriting the library from the ground up.
- [x] Update the copyright headers and LICENSE file (done as I move files).
- [x] Restructure the MSBuild files:
  - [x] Add `Directory.Build.props` and `Directory.Build.targets` for:
    - [x] Repository Root (including `global.json`.
    - [x] Sources
    - [x] Examples
    - [x] ~Tests~
- [x] Split the `LibUISharp` project into multiple projects (including empty projects for future work, including projects that are incomplete [LibUISharp/LibUISharp.UI]):
  - [x] LibUISharp (Removed from solution, split into other projects)
  - [x] LibUISharp.Core
  - [x] LibUISharp.Audio (Future)
  - [x] LibUISharp.CodeAnalysis.NativeCallGenerator (Future)
  - [x] ~LibUISharp.Runtime~
  - [x] LibUISharp.Native.Libui
  - [x] LibUISharp.Native.Miniaudio (Future)
  - [x] LibUISharp.UI
  - [x] LibUISharp.UI.Extras (Future)
- [x] Setup new CI with Azure Pipelines initially, then (possibly) to GitHub Actions in the future.
- [ ]  Setup the libui repo with Azure pipelines, and commit build artifacts to this repository (binaries).
- [ ]  Setup the miniaudio repo with Azure pipelines, and commit build artifacts to this repository (binaries).
- [ ]  Setup the zstd repo with Azure pipelines, and commit build artifacts to this repository (binaries).
- [x] Setup Nuget for stable, MyGet for prerelease~, and GitHub for other builds~.
- [x] Update README to reflect changes 
- [x] Create a `.temp` folder in the root for old files that will be rewritten after this PR is merged.
- [x] Rename the project and all references to `LibUISharp`.
  - [x] Namespaces
  - [x] License Headers
  - [x] Markdown Files
  - [x] Package Metadata
  - [x] Project Name (GitHub, not part of PR)
  - [x] Azure Pipelines Project Name (will create a new project and new pipeline)
  - [x] All files that have `LibUISharp` in it's name.

### CODE REVIEW

**Comment by tom-corwin** [comment]
I need to decide on CLS compliance, also. Kinda want it so it can be used with F#/VB.NET. kinda don't to leverage C#'s true potential.

**Comment by tom-corwin** [comment]
> I need to decide on CLS compliance, also. Kinda want it so it can be used with F#/VB.NET. kinda don't to leverage C#'s true potential.

I've decided. No CLS.

**Comment by tom-corwin** [comment]
NOTE-TO-SELF: https://github.com/andlabs/libui/issues/544#issuecomment-991042285

**Comment by tom-corwin** [comment]
Woot woot! The  It *should* build, and create a simple, empty window. *Should* being used loosely, as I haven't tested it yet.

**Comment by tom-corwin** [comment]
Does not build, but it will here in an hour or so.

**Comment by tom-corwin** [comment]
I didn't realize that in updateing the CI, there would be over 100 checks for just CI builds. Oh well, 6 OSs are covered.

**Comment by tom-corwin** [comment]
Definitely changing the CI to build Debug and Release configurations in the same job. This should literally cut the amount of jobs in half.

**Comment by simplexidev** [comment]
Project will be renamed in the next day or so to `sdfx`. See PR description and #41 for more information.

**Comment by simplexidev** [comment]
I am hoping to have this done and merged for the new year, but, as usual, the holidays make it a tad difficult to find time. 🙁

**Comment by simplexidev** [comment]
Sorry I couldn't get this done by New Years. Will 100% be done by the end of New Years Day.

**Comment by simplexidev** [comment]
This is just going to be merged early. Cannot setup the CI properly without it being on the `main` branch.

**Pull request merged**
